/* 
**  mod_location.c -- Apache sample location module
**  [Autogenerated via ``apxs -n location -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_location.c
**
**  Then activate it in Apache's apache2.conf file for instance
**  for the URL /location in as follows:
**
**    #   apache2.conf
**    LoadModule location_module modules/mod_location.so
**    <Location /location>
**         name "localhost"
**         tags "a cab ac"
**         glat "0"
**         glon "0"
**         link "http://localhost/location"
**         grad "10"
**         vote "10"
**         SetHandler location
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /location and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/location 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    location-name: "location"
**    location-link: "http://localhost/location/"
**    location-glat: "0"
**    location-glon: "0"
**    location-grad: "0"
**    location-vote: "0"
**
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"
#include "location.h"

/* The sample content handler */
static int location_handler(request_rec *r)
{
    if (strcmp(r->handler, "location")) {
        return DECLINED;
    }
    r->content_type = "text/html";      

    if (!r->header_only) {
        ap_rputs("Location:\n", r);
        ap_rputs(name, r);
        ap_rputs(link, r);
        ap_rputs(glat, r);
        ap_rputs(glon, r);
        ap_rputs(grad, r);
        ap_rputs(vote, r);
    }
    return OK;
}

static void location_register_hooks(apr_pool_t *p)
{
    ap_hook_handler(location_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA location_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    location_register_hooks  /* register hooks                      */
};

